version: '3'
services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  mongodb:
      image: mongo:latest
      volumes:
        - mongodb-data:/data/db
      ports:
        - 27017:27017
volumes:
  redis-data:
  mongodb-data: